on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Push to destination repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --unset http.https://github.com/.extraheader
          git push https://x-access-token:$PAT@github.com/psacc/minimalist-portfolio.git HEAD:master